name: Build and Run WowItemVersion project

on: [push, pull_request]
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: 'recursive'
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Run WowItemVersion
        run: dotnet run --project WowItemVersion --configuration Release
        
      - name: Run WowItemVersion
        run: dotnet run --no-build --configuration Release --project WowItemVersion > wow_item_to_expansion.json

      - name: Create artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: WowItemVersion_${{ matrix.os }}_${{ matrix.dotnet-version }}
          path: wow_item_to_expansion.json